import cron from 'node-cron';
import Audio from '#/model/audio';
import AutoPlaylist from '#/model/autoGeneratedPlaylist';



const generatedPlaylist = async () => {
    const result = await Audio.aggregate([
        {
            $sort: { likes: -1 }
        }, {
            $sample: { size: 20 }
        }, {
            $group: {
                _id: "$category",
                audios: { $push: "$$ROOT._id" }
            }
        }
    ]);

    result.map(async (item) => {
        await AutoPlaylist.updateOne(
            { title: item._id.toString() },
            { $set: { items: item.audios } },
            { upsert: true }
        )

    })
}

cron.schedule('0 0 * * *', async () => {
    await generatedPlaylist()
});